# Generated by Django 5.0 on 2023-12-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_db',
            old_name='image',
            new_name='profile_image',
        ),
    ]
