# Generated by Django 5.0 on 2024-01-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0004_login_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_db',
            name='email_id',
        ),
    ]
